### PR TITLE
Import AUTHORS from nose

### PR DESCRIPTION
**Pull request by astatide**
The following PR adds the original AUTHORS file from the nose repository, ensuring proper attribution is given.

### CODE REVIEW

**Comment by emilazy** [comment]
Could you add Michael Mintz and Christian Clauss so that this has a more complete list of contributors/copyright holders?

**Comment by astatide** [comment]
Hmmm, in that case, it might be better to move this up a directory (as it is, I just tried to pull it into the original location of the AUTHORS file from the nose directory).

**Comment by emilazy** [comment]
It’s in the root of the upstream nose repository, too, not the `nose` subdirectory both share, so I think that placement with the rest of the meta files rather than the Python source directory makes more sense.

**Comment by astatide** [comment]
Ah, I thought the subdirectory they shared was a little different.  However, I think even if that were the case, it makes more sense to have it in the root and with all authors.  Thank you for the suggestion!

**Review by emilazy — APPROVED** [review]
Looks good to me now, but @mdmintz will of course need to review/merge.

**Comment by mdmintz** [comment]
Do we know why "John Szakmeister" is missing from the original AUTHORS file? He was a major contributor to the original nose. (A few other missing too. I'm looking into it)

**Comment by mdmintz** [comment]
Take a look at https://github.com/mdmintz/pynose/pull/32 (I added missing authors, reordered a bit based on lines of code)

**Comment by mdmintz** [comment]
Completed in https://github.com/mdmintz/pynose/pull/32
Now there are 38 authors listed, including some ones that were missing in https://github.com/nose-devs/nose/blob/master/AUTHORS

**Comment by astatide** [comment]
Look, I’ll be honest with you.  I opened this PR because you complained you were busy and had a lot of things to take care of, and I wanted to provide a way for you to make it look like you weren’t just trying to make it look like you did all the work on this project.  So your response of opening a second PR that’s a slightly modified version of this, merging yours, and closing this?  Really makes it look like you’re doing exactly that.

Sure, it took me less than 30 seconds to make this PR and I have no interest in actually contributing to your project, but you claimed you were busy and this was too much work so I took a proactive helpful approach. 

 Making a separate PR that your GitHub history gets credit for (your GitHub history already has credit for the massive commit/PR you did with the nose project here) is literally the exact behavior you should be avoiding and that you claimed you weren’t doing.

**Pull request closed without merging**
